#' Export a table for PheWAS analysis in plink
#'
#'This function will export a table created by createPhewasTable as a secondary
#'phenotype file for use in plink.
#'
#'Plink \url{https://www.cog-genomics.org/plink2} is a commonly used genetics
#'analysis tool heavily optimized for handling GWAS. This function will export
#'a phenotype file as expected by plink which can be helpful for analysis.
#'
#' The \code{translateIDs} options allows users to supply their own FID/IID
#' pairs in case they are not identical (common in sets with no family information).
#'
#' @param phenotypes The phenotype file generated by createPhewasTable (or similar).
#' @param file The path and filename for the phenotype file.
#' @param translateIDs If true, the function will duplicate the first column
#' (presumably the unique id) into two columns named FID and IID. The default
#' (TRUE) will handle createPhewasTable input. FALSE requires columns named
#' "FID" and "IID" to be present.
#'
#' @return a file usable in plink
#' @importFrom utils write.table
#' @export
#'
#' @examples \donttest{
#' #Generate some example data
#' ex=generateExample(hit="335")
#' #Extract the two parts from the returned list
#' id.icd9.count=ex$id.icd9.count
#' genotypes=ex$genotypes
#' #Create the PheWAS code table- translates the icd9s, adds exclusions, and reshapes to a wide format
#' phenotypes=createPhewasTable(id.icd9.count)
#' #Export the file for use in plink
#' plinkPhewasExport(phenotypes, file="my.example.pheno")
#' }
plinkPhewasExport <- function(phenotypes, file="plink.pheno", translateIDs=TRUE) {
  if(translateIDs) {
    name_id=names(phenotypes)[1]
    #Create the new ID columns
    phenotypes$FID=phenotypes[[1]]
    phenotypes$IID=phenotypes[[1]]
    #Remove the old id column as long as it wasn't one we need
    if(!(name_id %in% c("FID","IID"))) phenotypes=phenotypes[,-1]
  }
  #Make sure the IDs are in the proper order
  pheno.out=phenotypes %>% select(FID, IID, everything())
  pheno.out=lapply(pheno.out,function(x){
    if(is(x, 'logical')){
      x=ifelse(is.na(x),-9,ifelse(x,2,1))
    }
    x
  })
  write.table(data.frame(pheno.out,check.names = F), file = file, row.names = FALSE, quote = FALSE, sep="\t")
}
